import StyledComponentsRegistry from "./lib/registry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "bookmarkbunker",
  description: "Generated by lhyjjg",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html>
        <body>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </>
  );
}
