"use client";

import StyledComponentsRegistry from "../lib/registry";
import type { Metadata } from "next";

import Header from "../app/components/header";

export const metadata: Metadata = {
  title: "bookmarkbunker",
  description: "Generated by lhyjjg",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html>
        <body>
          <StyledComponentsRegistry>
            <Header />
            {children}
          </StyledComponentsRegistry>
        </body>
      </html>
    </>
  );
}
